### ISSUE TITLE
Evaluate addition of 'jekyll-toc' plugin for auto-generation of per-page TableOfContents

### ISSUE THREAD

**Issue by torbjoernk** [JLESC/jlesc.github.io#109]
Just learned about the Jekyll plugin https://github.com/toshimaru/jekyll-toc. This gives the ability to use `{{ content | toc }}` to generate a table of contents (headings) for a page. We should evaluate its use for the JLESC website and the pages, where it might come in handy (e.g. project pages).

**Comment by pancetta** [comment]
Looks interesting. Does it play well with our 3rd/4th level headings? And: if we do this, we need to adapt the report generator to exclude the toc.

**Comment by torbjoernk** [comment]
I did some first testing and the current state of the plugin does not serve our purpose.

The content of the page is always injected right below the TOC. That way we cannot have the TOC in the aside and an article's content where it is right now. I've opened an issue for the plugin: toshimaru/jekyll-toc#5
