### ISSUE TITLE
Lengthy links do not look so nice 

### ISSUE THREAD

**Issue by pancetta** [JLESC/jlesc.github.io#125]
Lengthy links in events do not look so nice, see http://jlesc.github.io/events/1st-jlesc-workshop/. Can we fix that?

**Comment by torbjoernk** [comment]
Is clipping the displayed URL by ellipses an option?

```
+------------------+
| domain.com...    |
+------------------+
```

**Comment by pancetta** [comment]
Sure! Whatever it takes..

**Comment by pancetta** [comment]
Or you could just have an icon?
