### ISSUE TITLE
One meta-data-block to rule them all

### ISSUE THREAD

**Issue by pancetta** [JLESC/jlesc.github.io#136]
Is there a way to have just one set of YAML variables for the main page and all sub-pages? Currently, we need to specify the meta-data for each sub-page.

**Comment by torbjoernk** [comment]
Unfortunately, this is not possible. At least when we want the meta data in the aside on all sub-pages.

**Why?**  
Jekyll processes each source file separately and has no direct knowledge of the other pages when rendering one specific page. Probably, it would be possible to write a plugin to leverage that, but I try to avoid that complexity.

However, I could add a YAML front matter field for disabling the aside completely for a specific sub-page.

**Comment by pancetta** [comment]
Na, never mind. I like it the way it is now (except for the bloat).
