### ISSUE TITLE
Weird "," in the references

### ISSUE THREAD

**Issue by pancetta** [JLESC/jlesc.github.io#147]
If a paper has multiple authors, the last author is has a `,` right in front of the `&`, e.g. 

> A, B, & C

This doesn't look nice...

**Comment by pancetta** [comment]
We should have a reference style that does `(A & B, 2001)` for up to two authors or `(A et al., 2001)` for more than two authors.

**Comment by pancetta** [comment]
Does [this](http://tex.stackexchange.com/questions/24460/how-do-i-truncate-the-author-list-and-substitute-et-al) help? `natbib` seems to be a good choice anyway..

**Comment by torbjoernk** [comment]
Ok, though the _natbib_ link does not help for [CSL](http://citationstyles.org/) and [Citeproc](//github.com/inukshuk/citeproc-ruby), I managed to improve the situation by switching from the [generic APA style](https://www.zotero.org/styles?q=apa%206th) to [Chicago author-date](https://www.zotero.org/styles?q=chicago-author-date).
