### ISSUE TITLE
Reformat BibTeX file to comply with convention

### ISSUE THREAD

**Issue by torbjoernk** [JLESC/jlesc.github.io#15]
The current BibTeX file's formatting doesn't comply with the formatting convention stated at the top of the file.

(_yes, the convention specification was added afterwards :wink:_)

**Comment by pancetta** [comment]
@torbjoernk: I'm not sure the specs are unambiguous. Do you want people to indent keys, entries or tags? Or all of them? So far I read "indent keys of entries" and this is what @isabelheisters did. At parallelintime.org, we don't do that but indent the tags...

**Comment by torbjoernk** [comment]
Yeah, right. That's a misunderstanding. I ment the tags/fields of an entry (author, title, etc.).

@isabelheisters, do you mind adjusting the documentation/specification in the bibtex file as well?
While you're at it, you can add that the continuation indent should be 2 as well:

```
@misc{
  abstract = {some long text,
    that is wrapped},
  title = ...
}
```
