### ISSUE TITLE
Some projects have wrong year headers

### ISSUE THREAD

**Issue by pancetta** [JLESC/jlesc.github.io#181]
The FMM report shows the wrong years in the headers. Also, the PM state "since December 2014". We need to change that.

Also: 
- http://jlesc.github.io/projects/ichpc_project/
- http://jlesc.github.io/projects/pmefr_project/

Please double check the others, too.

**Comment by acavelan** [comment]
All these projects show 2014/2015:
- eandb_project.md
- ichpc_project.md
- fmm_project.md
- ompss_argobots_project.md
- pmefr_project.md
- reducing_communication_sparse.md

Are these just typos, or copies from last year that need to be updated?

**Comment by pancetta** [comment]
Both, I guess. Those are the blueprints we put on the website initially
and people did not change them. For now, we should just change that to
2015/2016 and be done with it. Could you do that?
