### ISSUE TITLE
Add ImageMagick error to troubleshooting

### ISSUE THREAD

**Issue by leobago** [JLESC/jlesc.github.io#211]
I was having the following error while trying to [test locally](https://github.com/JLESC/jlesc.github.io/wiki/Testing-Locally):

`$ bundle exec jekyll serve --watch`
`Configuration file: .../jlesc.github.io/_config.yml`
`Source: .../jlesc.github.io`
`Destination: .../jlesc.github.io/_site`
`Incremental build: disabled. Enable with --incremental`
`Generating...`
`undefined method`destroy!' for nil:NilClass`
`  Liquid Exception: undefined method `destroy!' for nil:NilClass in .../jlesc.github.io/_events_past/2015-06-29-3rd-jlesc-workshop/schedule.html`
`jekyll 3.1.1 | Error:  undefined method`destroy!' for nil:NilClass`

This occurs when ImageMagick is not installed properly in the machine. I know that the Wiki starts by 

> make sure to have ImageMagick's command line tool available on your machine

but maybe it could be useful to also add the error message and the solution in the [troubleshooting](https://github.com/JLESC/jlesc.github.io/wiki/Troubleshooting).

**Comment by pancetta** [comment]
Agreed and done: https://github.com/JLESC/jlesc.github.io/wiki/Troubleshooting#liquid-exception-undefined-method-destroy-for-nilnilclass-in-

Yet, in my case this error just disappeared without any intervention from my side. Weird...
