### ISSUE TITLE
Jumping header

### ISSUE THREAD

**Issue by pancetta** [JLESC/jlesc.github.io#28]
If you go to the main page http://jlesc.github.io/ and then to e.g. http://jlesc.github.io/about/index.html the header shifts slightly to the left. This always seem to occur if you go from a page without dropdown (e.g. http://jlesc.github.io/education/index.html) to a page inside dropdown menu.

**Comment by torbjoernk** [comment]
This is caused on switching between sites with and without a vertical scroll bar.

Wont fix that.
