### ISSUE TITLE
Missing character in a command

### ISSUE THREAD

**Issue by xRahul** [JLESC/jlesc.github.io#368]
On the Troubleshooting page under the heading-
[**Liquid Exception: "\xE6" on US-ASCII**](https://github.com/JLESC/jlesc.github.io/wiki/Troubleshooting#liquid-exception-xe6-on-us-ascii)

There's `T` missing in command. Change:
`LC_ALL=en_US.UF-8 jekyll serve --watch`
to:
`LC_ALL=en_US.UTF-8 jekyll serve --watch`

**Comment by pancetta** [comment]
Indeed, sorry for that! Fixed.
