### ISSUE TITLE
Update wiki

### ISSUE THREAD

**Issue by pancetta** [JLESC/jlesc.github.io#46]
In particular:
- [x] projects + templates
- [x] visit database
- [x] people
- [x] LaTeX Report Generator

**Comment by torbjoernk** [comment]
I think, most of the stuff for the casual contributor is done. I'll proof-read everything tomorrow and add the missing page on the LaTeX Report Generator.

**Comment by torbjoernk** [comment]
Should be sufficient now.

@pancetta, feel free to close this, in case you're happy with the wiki.
