### ISSUE TITLE
BibTeX Key

### ISSUE THREAD

**Issue by isabelheisters** [JLESC/jlesc.github.io#51]
Maybe we standardize the BibTeX Keys at the References?

**Comment by pancetta** [comment]
What would you propose?

**Comment by torbjoernk** [comment]
I propose this pattern `[FirstAuthorSurname]EtAl[YEAR]`. In case the first author has multiple publications in one year, arbitrarily append a letter `a`, `b` etc.

SpeckEtAl2014, SpeckEtAl2015a, SpeckEtAl2015b

For single-author-papers omit the `EtAl` part.

**Comment by pancetta** [comment]
Agreed. However, the "EtAl" should only be there if the paper has more than 2 authors. Otherwise, use `[FirstAuthorSurname][SecondAuthorSurname][YEAR]`.

**Comment by pancetta** [comment]
Can we put this into the notes/description somewhere?
