### ISSUE TITLE
Fill "grants" page

### ISSUE THREAD

**Issue by pancetta** [JLESC/jlesc.github.io#60]
Simply use http://publish.illinois.edu/jointlab-esc/grants/ to fill the "grants"-page in the "about"-tree.

**Comment by pancetta** [comment]
@isabelheisters OK, this does look weird, I agree. How about removing the headings and just having a list of Grants?

**Comment by torbjoernk** [comment]
I suggest using definition lists. We use the _kramdown_ Markdown parser and thus, all its nice Markdown extensions should work out of the box.

For _kramdown_'s definition list syntax [see its documentation](http://kramdown.gettalong.org/syntax.html#definition-lists).
