### ISSUE TITLE
Add external links to events

### ISSUE THREAD

**Issue by pancetta** [JLESC/jlesc.github.io#75]
Does it make sense to have external links in the meta-data? I'd like to put in the links for the workshops and I guess the best place to do that is in the meta-data..

**Comment by pancetta** [comment]
An since we're already talking: we have this nice feature at parallelintime.org to have a link to the web archive. How about that for JLESC?

**Comment by torbjoernk** [comment]
A homepage of an event can already be added and used via the `event_url` and `event_short_url` YAML data. Unfortunately, they somehow got removed from the template.

Yes, I know, another undocumented feature :grin: 

I'll add the timemachine link.
