### ISSUE TITLE
Double surnames

### ISSUE THREAD

**Issue by isabelheisters** [JLESC/jlesc.github.io#86]
What about the ID of people with a double surname? 
Should I write both names like surname1_nurname2 or only one of them or surname1-surname2 or surname1surname2?
Any agreeable proposal?

**Comment by torbjoernk** [comment]
I'd go with `surname1_surname2_initial`. Please, don't use simple dashes in the keys. Only lowercase characters, numbers and underscores.

**Comment by pancetta** [comment]
Yep, I agree.

**Comment by pancetta** [comment]
Fixed by PR #90
