### ISSUE TITLE
Add logos to events

### ISSUE THREAD

**Issue by pancetta** [JLESC/jlesc.github.io#91]
I'm not sure we need this, but I'd like to have the logos of the events either in the meta-data or somewhere else (see 4th workshop logo [here](http://www.fz-juelich.de/ias/jsc/EN/Expertise/Workshops/Conferences/JLESC-4/4th-jlesc-logo.png?__blob=poster)).

**Comment by torbjoernk** [comment]
It's already there but probably not 100% working. Should be fixed now.
